# Generated by Django 2.0.2 on 2018-04-25 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_id', models.CharField(max_length=50, unique=True, verbose_name='机器编号')),
                ('hostname', models.CharField(max_length=50, unique=True, verbose_name='主机名')),
            ],
        ),
    ]
