# Generated by Django 2.0.2 on 2018-04-28 05:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='日期')),
                ('name', models.CharField(max_length=50, verbose_name='进程名')),
                ('percent', models.FloatField(max_length='50', verbose_name='百分比')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.Host')),
            ],
        ),
    ]
